const PROJECT_TYPES = [
  {
    category: "🌐 Web & Application Development",
    items: [
      { name: "E‑Commerce platforms", price: 12000 },
      { name: "Learning Management Systems (LMS)", price: 15000 },
      { name: "Social networking sites", price: 20000 },
      { name: "Blogging platforms / CMS", price: 8000 },
      { name: "Online booking/reservation systems", price: 10000 },
      { name: "Portfolio/personal branding websites", price: 5000 },
      { name: "Event management systems", price: 12000 },
      { name: "Donation & fundraising platforms", price: 9000 },
      { name: "Online forums/discussion boards", price: 8000 },
      { name: "Job boards & recruitment portals", price: 14000 },
    ],
  },
  {
    category: "📊 Business & Enterprise Solutions",
    items: [
      { name: "CRM systems", price: 18000 },
      { name: "Inventory management systems", price: 12000 },
      { name: "Project management dashboards", price: 15000 },
      { name: "Expense tracking & budgeting tools", price: 9000 },
      { name: "Workflow automation tools", price: 14000 },
      { name: "ERP systems", price: 25000 },
      { name: "POS integration platforms", price: 12000 },
      { name: "HR management systems", price: 16000 },
      { name: "Document management systems", price: 10000 },
      { name: "Business intelligence dashboards", price: 20000 },
    ],
  },
  {
    category: "🛡️ Security & Infrastructure",
    items: [
      { name: "Authentication & authorization systems", price: 10000 },
      { name: "Secure file sharing platforms", price: 12000 },
      { name: "Cybersecurity monitoring dashboards", price: 18000 },
      { name: "Role-based access control systems", price: 9000 },
      { name: "Data encryption & backup solutions", price: 11000 },
      { name: "Network monitoring tools", price: 14000 },
      { name: "Cloud migration platforms", price: 20000 },
      { name: "Identity management systems", price: 15000 },
      { name: "API security gateways", price: 12000 },
      { name: "Compliance management systems", price: 18000 },
    ],
  },
  {
    category: "📱 Mobile & Cross-Platform",
    items: [
      { name: "Mobile banking apps", price: 25000 },
      { name: "Food delivery apps", price: 18000 },
      { name: "Ride-hailing apps", price: 22000 },
      { name: "Fitness tracking apps", price: 15000 },
      { name: "E-learning mobile apps", price: 20000 },
      { name: "Chat/messaging apps", price: 18000 },
      { name: "Mobile payment wallets", price: 22000 },
      { name: "Augmented Reality (AR) apps", price: 28000 },
      { name: "IoT device control apps", price: 25000 },
      { name: "Smart home management apps", price: 30000 },
    ],
  },
  {
    category: "📊 Data & Analytics",
    items: [
      { name: "Data visualization dashboards", price: 12000 },
      { name: "Predictive analytics tools", price: 20000 },
      { name: "AI-powered recommendation engines", price: 25000 },
      { name: "Sentiment analysis platforms", price: 18000 },
      { name: "Big data processing pipelines", price: 28000 },
      { name: "Machine learning model deployment platforms", price: 30000 },
      { name: "Real-time analytics systems", price: 22000 },
      { name: "Survey & feedback analysis tools", price: 10000 },
      { name: "KPI monitoring dashboards", price: 15000 },
      { name: "Business forecasting tools", price: 20000 },
    ],
  },
  {
    category: "🌍 Community & Advocacy",
    items: [
      { name: "Waste management advocacy websites", price: 8000 },
      { name: "Environmental awareness portals", price: 10000 },
      { name: "Civic engagement platforms", price: 12000 },
      { name: "Digital safety portals for schools", price: 9000 },
      { name: "Online petition platforms", price: 8000 },
      { name: "Community resource directories", price: 10000 },
      { name: "Volunteer management systems", price: 12000 },
      { name: "Nonprofit fundraising platforms", price: 9000 },
      { name: "Public health awareness sites", price: 11000 },
      { name: "Local government service portals", price: 15000 },
    ],
  },
  {
    category: "🎨 Creative & Media",
    items: [
      { name: "Online design collaboration tools", price: 15000 },
      { name: "Digital storytelling platforms", price: 12000 },
      { name: "Video streaming sites", price: 25000 },
      { name: "Music sharing platforms", price: 20000 },
      { name: "Photo gallery/portfolio sites", price: 8000 },
      { name: "Podcast hosting platforms", price: 12000 },
    ],
  },
];

module.exports = { PROJECT_TYPES };
